
server.port : 8080


## Database Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ejdkdlqlwjs0608)^)*
    url: jdbc:mysql://ipaddr:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&serverTimezone=Asia/Seoul

#JPA Setting
# Use mysql
  jpa:
    show_sql : true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true            # Print SQL Query
        format_sql: true          # Show SQL in Format
        use_sql_comments: true    # Print Debuging Info

#logging Level Setting
logging:
  level:
    org:
      hibernate: info
